module.exports = {
  UPDATE_FORM_INPUT: "UPDATE_FORM_INPUT",
  LOGIN_REQUEST: "LOGIN_REQUEST",
  REGISTER_REQUEST: "REGISTER_REQUEST",
  UPDATE_USER: "UPDATE_USER",
  LOGOUT_REQUEST: "LOGOUT_REQUEST",
  BOOK_SEARCH_REQUEST: "BOOK_SEARCH_REQUEST",
  //for adding books
  BOOK_ADD_REQUEST: "BOOK_ADD_REQUEST",
  ADD_BOOK: "ADD_BOOK",
  ADD_TO_LIBRARY: "ADD_TO_LIBRARY",
  //for removing books
  BOOK_REMOVE_REQUEST: "BOOK_REMOVE_REQUEST",
  REMOVE_BOOK: "REMOVE_BOOK",
  REMOVE_FROM_LIBRARY: "REMOVE_FROM_LIBRARY"
};
