module.exports = {
  UPDATE_FORM_INPUT: "UPDATE_FORM_INPUT",
  LOGIN_REQUEST: "LOGIN_REQUEST",
  REGISTER_REQUEST: "REGISTER_REQUEST",
  UPDATE_USER: "UPDATE_USER",
  LOGOUT_REQUEST: "LOGOUT_REQUEST"
};
